import { estimateWithdrawal, parsePerformanceCsv, previewPerformanceImports, simulateEvaluation, summarizePerformanceTrades } from './performance-model.mjs';

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const currency=value=>value==null||value===''||!Number.isFinite(Number(value))?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(value));
const number=value=>value===Infinity?'∞':value==null||Number.isNaN(Number(value))?'—':new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(Number(value));
const percent=value=>value==null?'—':`${number(value)}%`;
const emptyProfile={startingBalance:'',profitTarget:'',dailyLossLimit:'',maxDrawdown:'',drawdownType:'static',minimumDays:'',consistencyPct:'',dailyResetTime:'00:00',sessionTimeZone:'',safetyBuffer:'',splitPct:'',minimumPayout:'',maximumPayout:''};
let pendingImport=null;

export function initializePerformanceState(source={}){
  const state={datasets:[],activeDatasetId:'',activeTab:'geral',showImport:false,evaluationProfile:{...emptyProfile},withdrawalProfile:{...emptyProfile},audit:[],...(source&&typeof source==='object'?source:{})};
  for(const key of ['datasets','audit'])if(!Array.isArray(state[key]))state[key]=[];
  state.datasets=state.datasets.filter(Boolean).map(set=>({...set,trades:Array.isArray(set.trades)?set.trades:[],summaries:Array.isArray(set.summaries)?set.summaries:[],sources:Array.isArray(set.sources)?set.sources:[]}));
  state.activeTab=['geral','aprovacao','saque'].includes(state.activeTab)?state.activeTab:'geral';
  state.evaluationProfile={...emptyProfile,...(state.evaluationProfile||{})};state.withdrawalProfile={...emptyProfile,...(state.withdrawalProfile||{})};
  if(!state.datasets.some(set=>set.id===state.activeDatasetId))state.activeDatasetId=state.datasets[0]?.id||'';
  return state;
}

function activeSet(state){return state.datasets.find(set=>set.id===state.activeDatasetId)||null;}
function statusBadge(status){const labels={passed:'META ATINGIDA',failed:'REGRA VIOLADA',in_progress:'EM ANDAMENTO',pending:'CONFIGURE AS REGRAS',unavailable:'DADOS INSUFICIENTES',estimate:'ESTIMATIVA',below_minimum:'ABAIXO DO MÍNIMO',within_limit:'DENTRO DO LIMITE',met:'ATINGIDA',not_configured:'NÃO CONFIGURADO'};const cls=['passed','met','within_limit','estimate'].includes(status)?'good':['failed','unavailable','below_minimum'].includes(status)?'bad':'neutral';return `<span class="pl-badge ${cls}">${labels[status]||esc(status)}</span>`;}
function metric(label,value,caption,positive=false){return `<article class="pl-metric"><span>${label}</span><strong class="${positive?'positive':''}">${value}</strong><small>${caption}</small></article>`;}
function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||''}</tbody></table></div>`;}
function panel(title,content,tag=''){return `<section class="panel pl-panel"><div class="panel-heading"><h2>${title}</h2>${tag?`<span class="panel-tag">${tag}</span>`:''}</div>${content}</section>`;}
function kpiSummary(set){const grid=set?.trades?.length?summarizePerformanceTrades(set.trades,set.sequenceReliable):null;const summary=set?.summaries?.[0]?.summary;return grid?{...grid,source:'CSV Grid'}:summary?{tradeCount:summary.tradeCount,netProfit:summary.netProfit,profitFactor:summary.profitFactor,winRate:summary.winRate, maxDrawdown:summary.drawdown,source:'Relatório agregado'}:null;}
function chart(curve){if(!curve.length)return `<div class="pl-chart-empty">A curva de equity aparece quando há operações em ordem confiável.</div>`;const values=curve.map(p=>p.equity),min=Math.min(0,...values),max=Math.max(0,...values),span=max-min||1,w=760,h=210,pad=14;const pts=values.map((v,i)=>`${pad+(curve.length===1?0:i/(curve.length-1))*(w-pad*2)},${h-pad-(v-min)/span*(h-pad*2)}`);const baseline=h-pad-(0-min)/span*(h-pad*2);return `<div class="pl-chart"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Curva acumulada de resultado por operação"><defs><linearGradient id="pl-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#41d6b1" stop-opacity=".28"/><stop offset="1" stop-color="#41d6b1" stop-opacity="0"/></linearGradient></defs><line x1="${pad}" x2="${w-pad}" y1="${baseline}" y2="${baseline}" stroke="#344e68" stroke-dasharray="4 5"/><polygon points="${pad},${baseline} ${pts.join(' ')} ${w-pad},${baseline}" fill="url(#pl-area)"/><polyline points="${pts.join(' ')}" fill="none" stroke="#48d5b2" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg><div class="pl-chart-labels"><span>${esc(curve[0].date)}</span><span>${esc(curve.at(-1).date)}</span></div></div>`;}
function importPanel(state){const preview=pendingImport?.preview;return `<section class="panel pl-import"><div class="panel-heading"><div><h2>Importar relatórios NinjaTrader</h2><p class="panel-description">CSV lido neste navegador · relatório agregado ou Grid com uma operação por linha.</p></div><button type="button" class="button secondary" data-pl="toggle-import">${state.showImport?'Fechar':'＋ Importar CSV'}</button></div>${state.showImport?`<form data-pl-form="import" class="pl-import-form"><label>Arquivos CSV<input type="file" name="files" accept=".csv,text/csv" multiple required></label><div class="pl-import-actions"><button class="button primary" type="submit">Pré-visualizar arquivos</button><span>Grid: Profit + Date (horário recomendado). Relatório: lucro líquido e total de negociações.</span></div><div class="form-errors" role="alert"></div></form>`:''}${preview?`<div class="pl-preview"><div><strong>Prévia pronta</strong><span>${preview.records.length} trades · ${preview.summaries.length} resumo(s) agregado(s) · ${preview.errors.length} linha(s) com erro</span></div>${preview.duplicates?`<p class="pl-alert">${preview.duplicates} possível(is) duplicata(s) detectada(s). Por padrão, trades marcados serão ignorados.</p>`:''}${preview.overlaps.length?`<p class="pl-alert">Períodos coincidentes: ${preview.overlaps.map(esc).join(' · ')}. Confira se os arquivos se sobrepõem antes de importar.</p>`:''}${preview.warnings.map(w=>`<p class="pl-note">${esc(w)}</p>`).join('')}${preview.errors.length?`<p class="pl-alert">${preview.errors.slice(0,5).map(esc).join('<br>')}</p>`:''}<label class="pl-check"><input type="checkbox" name="include-duplicates"> Incluir também as possíveis duplicatas</label><label>Nome do conjunto<input name="dataset-name" value="${esc(pendingImport.name)}" maxlength="80"></label><div class="pl-import-actions"><button class="button primary" type="button" data-pl="confirm-import">Confirmar importação</button><button class="button secondary" type="button" data-pl="cancel-import">Cancelar prévia</button></div></div>`:''}</section>`;}

function renderGeneral(set){
  if(!set)return `<div class="pl-empty"><div class="pl-empty-mark">↗</div><h2>Seu desempenho, com contexto.</h2><p>Importe um relatório do NinjaTrader para começar. O CSV Grid preserva a sequência e libera a curva de equity e as simulações.</p><button class="button primary" data-pl="toggle-import">Importar primeiro CSV</button></div>`;
  const summary=kpiSummary(set),grid=set.trades?.length? summarizePerformanceTrades(set.trades,set.sequenceReliable):null;
  if(!summary)return `<div class="pl-empty"><h2>Este conjunto não tem dados analisáveis.</h2><p>Abra Importar CSV e envie um relatório agregado ou Grid com a coluna Profit.</p></div>`;
  const dd=summary.maxDrawdown==null?'Indisponível':currency(summary.maxDrawdown),win=summary.winRate==null?'—':percent(summary.winRate);
  const ddSource=grid?(set.sequenceReliable?'Calculado na ordem do Grid':'Indisponível · sequência ambígua'):'Resumo informado pelo relatório';
  const cards=`<div class="pl-metrics">${metric('Lucro líquido',currency(summary.netProfit),'Fonte: '+summary.source,Number(summary.netProfit)>=0)}${metric('Operações',number(summary.tradeCount),'Trades no escopo analisado')}${metric('Profit factor',number(summary.profitFactor),'Ganhos brutos ÷ perdas brutas')}${metric('Taxa de acerto',win,'Resultados vencedores')}${metric('Drawdown máximo',dd,ddSource)}</div>`;
  const summaries=set.summaries?.length?panel('Relatórios agregados',table(['Período','Arquivo','Trades','Lucro líquido','Profit factor','Acerto','Drawdown informado'],set.summaries.map(item=>`<tr><td>${esc(item.summary.period||'Não identificado')}</td><td>${esc(item.filename)}</td><td>${number(item.summary.tradeCount)}</td><td>${currency(item.summary.netProfit)}</td><td>${number(item.summary.profitFactor)}</td><td>${percent(item.summary.winRate)}</td><td>${currency(item.summary.drawdown)}</td></tr>`).join('')),'Cada relatório permanece separado do Grid'):'';
  const dirs=grid?.byDirection?.length?panel('Resultado por direção',table(['Direção','Trades','Resultado líquido'],grid.byDirection.map(item=>`<tr><td>${esc(item.side)}</td><td>${number(item.trades)}</td><td>${currency(item.profit)}</td></tr>`).join(''))):'';
  const monthly=grid?.byDay?.length?(()=>{const map=new Map();for(const day of grid.byDay){const key=day.date.slice(0,7),row=map.get(key)||{count:0,profit:0};row.count+=day.trades;row.profit+=day.profit;map.set(key,row);}return panel('Evolução mensal',table(['Período','Operações','Resultado líquido'],[...map].sort((a,b)=>a[0].localeCompare(b[0])).map(([month,row])=>`<tr><td>${esc(month)}</td><td>${number(row.count)}</td><td>${currency(row.profit)}</td></tr>`).join('')));})():'';
  return `${cards}${grid?panel('Curva de equity',chart(grid.equityCurve),`${set.sequenceReliable?'ordem confiável':'sequência indisponível'} · ${grid.tradeCount} operações`):''}${summaries}${dirs}${monthly}<div class="info-strip"><span>ⓘ</span><p>Resumo agregado não contém a sequência dos trades. Drawdown de sequência e simulações usam apenas Grid individual em ordem confiável. Resultados dependem dos arquivos importados e não garantem aprovação ou saque.</p></div>`;
}

function profileFields(profile,kind){const fields=kind==='evaluation'?[['startingBalance','Saldo inicial'],['profitTarget','Meta de lucro'],['dailyLossLimit','Limite de perda diária'],['maxDrawdown','Drawdown máximo'],['minimumDays','Dias mínimos'],['consistencyPct','Limite de consistência (%)']]:[['startingBalance','Saldo de referência'],['safetyBuffer','Buffer de segurança'],['splitPct','Seu repasse (%)'],['minimumDays','Dias mínimos'],['minimumPayout','Saque mínimo'],['maximumPayout','Saque máximo']];const numeric=fields.map(([key,label])=>`<label>${label}<input type="number" name="${key}" step="0.01" min="0" value="${esc(profile[key])}" placeholder="Configurar"></label>`).join('');const session=kind==='evaluation'?`<label>Fuso horário do CSV<input type="text" name="sessionTimeZone" value="${esc(profile.sessionTimeZone)}" placeholder="Ex.: America/New_York"></label><label>Reinício diário no horário do CSV<input type="time" name="dailyResetTime" value="${esc(profile.dailyResetTime)}"></label>`:'';return numeric+session;}
function renderEvaluation(set,state){const grid=set?.trades?.length?set:null;const result=grid?simulateEvaluation(grid.trades,state.evaluationProfile,grid.sequenceReliable):{status:'unavailable',reason:'Importe um CSV Grid para simular a sequência de avaliação.'};const rules=result.rules?.map(rule=>`<div class="pl-rule"><div><strong>${esc(rule.label)}</strong><small>${rule.current==null?'—':number(rule.current)}${rule.target!=null?` / ${number(rule.target)}`:''}</small></div>${statusBadge(rule.status)}</div>`).join('')||'';return `<div class="pl-sim-grid"><section class="panel pl-profile"><div class="panel-heading"><div><h2>Regras da avaliação</h2><p class="panel-description">Configure os limites publicados pela sua prop firm.</p></div></div><form data-pl-form="evaluation"><div class="pl-fields">${profileFields(state.evaluationProfile,'evaluation')}<label>Tipo de drawdown<select name="drawdownType"><option value="static" ${state.evaluationProfile.drawdownType==='static'?'selected':''}>Estático</option><option value="trailing" ${state.evaluationProfile.drawdownType==='trailing'?'selected':''}>Trailing por trade</option></select></label></div><button class="button primary" type="submit">Salvar regras</button></form></section><section class="panel pl-result"><div class="panel-heading"><div><h2>Resultado da simulação</h2><p class="panel-description">${set?.trades?.length?`${set.trades.length} trades · ${set.sequenceReliable?'ordem preservada':'ordem ambígua'}`:'Aguardando CSV Grid'}</p></div>${statusBadge(result.status)}</div>${result.reason?`<div class="pl-empty-small"><p>${esc(result.reason)}</p></div>`:`<div class="pl-result-hero"><strong>${currency(result.equity)}</strong><span>Saldo projetado</span><small>Resultado ${currency(result.totalProfit)} · ${result.days} dias operados</small></div><div class="pl-rules">${rules}</div><p class="pl-note">${esc(result.assumption)}</p>${result.violatedTradeIds?.length?`<p class="pl-alert">Violação nos trades: ${result.violatedTradeIds.length}. Confira os limites configurados.</p>`:''}`}</section></div><div class="info-strip"><span>ⓘ</span><p>Simulação ilustrativa sobre os trades importados. Confira os termos oficiais, horários de sessão e regra de trailing da prop firm antes de tomar decisões.</p></div>`;}
function renderWithdrawal(set,state){const profile={...state.withdrawalProfile,sequenceReliable:Boolean(set?.sequenceReliable)};const result=set?.trades?.length?estimateWithdrawal(set.trades,profile):{status:'unavailable',reason:'Importe um CSV Grid para estimar cenários de saque.'};return `<div class="pl-sim-grid"><section class="panel pl-profile"><div class="panel-heading"><div><h2>Parâmetros de saque</h2><p class="panel-description">Use os valores e limites da conta que você quer simular.</p></div></div><form data-pl-form="withdrawal"><div class="pl-fields">${profileFields(state.withdrawalProfile,'withdrawal')}</div><button class="button primary" type="submit">Salvar parâmetros</button></form></section><section class="panel pl-result"><div class="panel-heading"><div><h2>Estimativa disponível</h2><p class="panel-description">Baseada no conjunto ativo e nos parâmetros preenchidos</p></div>${statusBadge(result.status)}</div>${result.totalProfit!=null?`<div class="pl-payout"><div><span>Saldo após operações</span><strong>${currency(result.endingBalance)}</strong></div><div><span>Lucro observado</span><strong>${currency(result.totalProfit)}</strong></div><div><span>Após buffer</span><strong>${currency(result.eligibleProfit)}</strong></div><div><span>Parcela configurada</span><strong>${currency(result.grossEligible)}</strong></div><div class="pl-payout-net"><span>Estimativa de saque</span><strong>${currency(result.netEstimate)}</strong></div></div>`:''}${result.reason?`<div class="pl-empty-small"><p>${esc(result.reason)}</p>${result.days!=null?`<small>${result.days} dias operados · valores seguem condicionados às regras configuradas.</small>`:''}</div>`:result.assumptions?.length?`<p class="pl-note">${result.assumptions.map(esc).join(' ')}</p>`:''}</section></div><div class="info-strip"><span>ⓘ</span><p>Estimativa matemática, não solicitação de saque. Elegibilidade real, regras de dias, buffers e limites variam conforme a prop firm.</p></div>`;}

function render(state){const set=activeSet(state),metrics=set?kpiSummary(set):null;return `<div class="performance-lab"><section class="pl-hero"><div class="pl-hero-copy"><span class="eyebrow">HUNTER · PERFORMANCE LAB</span><h2>Desempenho com contexto.<br><em>Decisões com clareza.</em></h2><p>Analise o histórico de operações e simule regras configuráveis de avaliação e saque.</p></div><div class="pl-hero-side"><span class="pl-hero-label">CONJUNTO ATIVO</span>${set?`<strong>${esc(set.name)}</strong><small>${set.trades?.length||0} operações ${set.summaries?.length?`· ${set.summaries.length} resumo(s)`:''}</small>`:`<strong>Nenhum arquivo importado</strong><small>Comece com relatório NinjaTrader ou CSV Grid</small>`}<button class="button primary" data-pl="toggle-import">＋ Importar dados</button></div></section><div class="pl-context"><label>Conjunto<select data-pl-select="dataset"><option value="">Selecione uma análise</option>${state.datasets.map(item=>`<option value="${esc(item.id)}" ${item.id===state.activeDatasetId?'selected':''}>${esc(item.name)}</option>`).join('')}</select></label>${set?`<span>Período ${esc(set.startDate||'—')} – ${esc(set.endDate||'—')} · origem ${set.sources?.map(esc).join(', ')||'CSV NinjaTrader'}</span><button type="button" class="text-button" data-pl="remove-dataset">Remover conjunto</button>`:`<span>Seus arquivos continuam separados das análises HSG e das contas de trader.</span>`}</div><nav class="pl-tabs" aria-label="Abas do Performance Lab">${[['geral','Geral'],['aprovacao','Aprovação'],['saque','Saque']].map(([id,label])=>`<button type="button" data-pl-tab="${id}" aria-current="${state.activeTab===id?'page':'false'}">${label}</button>`).join('')}</nav>${importPanel(state)}<div class="pl-content">${state.activeTab==='geral'?renderGeneral(set):state.activeTab==='aprovacao'?renderEvaluation(set,state):renderWithdrawal(set,state)}</div></div>`;}

export function renderPerformanceLab(view,state,persist){
  const draw=()=>{view.innerHTML=render(state);bind();};
  const save=()=>{persist(state);draw();};
  const bind=()=>{
    view.querySelectorAll('[data-pl-tab]').forEach(button=>button.onclick=()=>{state.activeTab=button.dataset.plTab;save();});
    view.querySelectorAll('[data-pl="toggle-import"]').forEach(button=>button.addEventListener('click',()=>{state.showImport=!state.showImport;pendingImport=null;draw();}));
    view.querySelector('[data-pl-select="dataset"]')?.addEventListener('change',event=>{state.activeDatasetId=event.target.value;save();});
    view.querySelector('[data-pl="cancel-import"]')?.addEventListener('click',()=>{pendingImport=null;draw();});
    view.querySelector('[data-pl="remove-dataset"]')?.addEventListener('click',()=>{if(!confirm('Remover este conjunto e seus dados do Performance Lab?'))return;state.datasets=state.datasets.filter(item=>item.id!==state.activeDatasetId);state.activeDatasetId=state.datasets[0]?.id||'';state.audit.unshift({action:'remove-dataset',at:new Date().toISOString()});save();});
    view.querySelector('[data-pl-form="evaluation"]')?.addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));state.evaluationProfile={...state.evaluationProfile,...data};state.audit.unshift({action:'update-evaluation-profile',at:new Date().toISOString()});save();});
    view.querySelector('[data-pl-form="withdrawal"]')?.addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));state.withdrawalProfile={...state.withdrawalProfile,...data};state.audit.unshift({action:'update-withdrawal-profile',at:new Date().toISOString()});save();});
    view.querySelector('[data-pl-form="import"]')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,files=[...form.elements.files.files],error=form.querySelector('.form-errors');if(!files.length){error.textContent='Selecione ao menos um arquivo CSV.';return;}const parsed=await Promise.all(files.map(async file=>parsePerformanceCsv(await file.text(),file.name)));const preview=previewPerformanceImports(state.datasets,parsed);if(!parsed.some(item=>item.kind==='summary'||item.records.length>0)){error.textContent=preview.errors.join(' ');return;}pendingImport={preview,name:files.length===1?files[0].name.replace(/\.csv$/i,''):`Análise ${new Date().toLocaleDateString('pt-BR')}`};draw();});
    view.querySelector('[data-pl="confirm-import"]')?.addEventListener('click',()=>{if(!pendingImport)return;const preview=pendingImport.preview;const form=view.querySelector('.pl-preview');const name=form.querySelector('[name="dataset-name"]').value.trim();if(!name){form.querySelector('[name="dataset-name"]').focus();return;}const includeDuplicates=form.querySelector('[name="include-duplicates"]').checked;const trades=preview.records.filter(trade=>includeDuplicates||!preview.duplicateIds.has(trade.id));if(!trades.length&&!preview.summaries.length){form.querySelector('[name="dataset-name"]').focus();return;}const dates=trades.map(t=>t.date).sort();const id=crypto.randomUUID();const set={id,name,trades,summaries:preview.summaries,sequenceReliable:preview.sequenceReliable,duplicateCount:preview.duplicates,overlaps:preview.overlaps,sources:[...new Set([...preview.records.map(t=>t.sourceFile),...preview.summaries.map(s=>s.filename)])],startDate:dates[0]||'',endDate:dates.at(-1)||'',importedAt:new Date().toISOString()};state.datasets.push(set);state.activeDatasetId=id;state.audit.unshift({action:'import',datasetId:id,trades:trades.length,summaries:set.summaries.length,duplicates:preview.duplicates,at:set.importedAt});pendingImport=null;state.showImport=false;save();});
  };
  draw();
}
